// This is the source code of AyuGram for Desktop.
//
// We do not and cannot prevent the use of our code,
// but be respectful and credit the original author.
//
// Copyright @Bush2021, 2026
#pragma once

#include "ayu/secret/secret_crypto.h"
#include "mtproto/sender.h"

// The Diffie-Hellman half of a secret chat, in two parts: a session-lived
// cache of `messages.dhConfig`, and three steps that turn a config and the
// peer's public value into the material a chat state needs. Nothing here
// holds a chat, sends anything other than `getDhConfig`, or logs a byte of
// the exchange. `AyuSecret::Chats` owns the requests, the states, and the
// order in which they change.
//
// The group (`p` and `g`) changes so rarely that the server answers
// `dhConfigNotModified` for as long as a client remembers it, so the cache
// keeps it for the session and only collects a new `random` each time.
// Callers that wait on one in-flight request share that `random`, which is
// safe because `GenerateDhSecret` XORs it with 256 locally generated bytes:
// the server's half never decides a secret exponent on its own.

namespace AyuSecret {

class DhConfigCache final {
public:
	using Callback = Fn<void(const Crypto::DhConfig*)>;

	explicit DhConfigCache(not_null<MTP::Sender*> api);
	~DhConfigCache();

	DhConfigCache(const DhConfigCache &other) = delete;
	DhConfigCache &operator=(const DhConfigCache &other) = delete;

	// The validated group, or null while this session has never seen one.
	// Its `random` belongs to the last answer, so only the steps that do
	// not draw a secret from it may use this instead of `request`.
	[[nodiscard]] const Crypto::DhConfig *cached() const;

	// Calls `done` with a validated group and a fresh `random`, or with
	// null when the server refused, answered with something that does not
	// validate, or sent `dhConfigNotModified` before anything was cached.
	void request(Callback done);

private:
	void apply(const MTPmessages_DhConfig &result);
	void finish(bool good);

	const not_null<MTP::Sender*> _api;
	Crypto::DhConfig _config;
	std::vector<Callback> _waiting;
	mtpRequestId _requestId = 0;
	bool _good = false;

};

// `a` and `g_a` for `messages.requestEncryption`. Both empty on failure.
struct CreatorRequest {
	bytes::vector a;
	bytes::vector gA;
};

[[nodiscard]] CreatorRequest MakeCreatorRequest(
	const Crypto::DhConfig &config);

// The shared key, `g_b` and the fingerprint for
// `messages.acceptEncryption`. `key` is empty when the peer's `g_a` does
// not validate, which is the one check that stands between us and a key a
// hostile party chose.
struct AcceptorAnswer {
	bytes::vector key;
	bytes::vector gB;
	int64 keyFingerprint = 0;
};

[[nodiscard]] AcceptorAnswer MakeAcceptorAnswer(
	const Crypto::DhConfig &config,
	bytes::const_span gA);

// The creator's side of the same key, from the `g_b` the answer carried.
// The caller compares `keyFingerprint` with the one the server sent and
// keeps the key only when the two agree.
struct CreatorKey {
	bytes::vector key;
	int64 keyFingerprint = 0;
};

[[nodiscard]] CreatorKey MakeCreatorKey(
	const Crypto::DhConfig &config,
	bytes::const_span gB,
	bytes::const_span a);

} // namespace AyuSecret
